### ISSUE TITLE
IOError: Could not load meta information

### ISSUE THREAD

**Issue by aszxnm** [abedavis/visbeat#4]
I need help...I don't know how to solve this problem.
Source: /home/gx/GX/code/visbeat-master/examples/test_files/dance1.mp4
Target: /home/gx/GX/code/visbeat-master/examples/test_files/music1.mp4
Video source at ./VisBeatAssets/VideoSources/dance1/
Calculating frames for dance1_Full...
Done.
Video source at ./VisBeatAssets/VideoSources/music1/
Calculating frames for music1_Full...
Done.
Warping dance1_240 to music1_240
Rendering 16 beats of result
16
16
target start: 0.371519274376
target end: 7.00081632653
target duration: 6.62929705215
[swscaler @ 0x5643f99be840] Warning: data is not aligned! This can lead to a speed loss
Calculating frames for None...
Done.
Issue loading audio for ./TEMP_dance1_240_TO_music1_240quad_sab_0_svb_0.mp4
Using bitrate of 20000k
stereo is False
Moviepy - Building video ./VisBeatAssets/VideoSources/dance1/Versions/Warps/maxheight_240//dance1_240_TO_music1_240quad_sab_0_svb_0.mp4.
MoviePy - Writing audio in %s
MoviePy - Done.                                                    
Moviepy - Writing video ./VisBeatAssets/VideoSources/dance1/Versions/Warps/maxheight_240//dance1_240_TO_music1_240quad_sab_0_svb_0.mp4

Moviepy - Done !                                               
Moviepy - video ready ./VisBeatAssets/VideoSources/dance1/Versions/Warps/maxheight_240//dance1_240_TO_music1_240quad_sab_0_svb_0.mp4
Calculating frames for None...
Done.
Traceback (most recent call last):
  File "dancefer.py", line 43, in <module>
    main(args);
  File "dancefer.py", line 31, in main
    nbeats=nbeats, output_path = output_path)
  File "/home/gx/anaconda3/envs/visbeat/lib/python2.7/site-packages/visbeat/__init__.py", line 244, in Dancefer
    warped_result_final = Video(path = final_output_path, num_frames_total=n_frames_total);
  File "/home/gx/anaconda3/envs/visbeat/lib/python2.7/site-packages/visbeat/Video.py", line 38, in __init__
    self.loadFile(num_frames_total=num_frames_total);
  File "/home/gx/anaconda3/envs/visbeat/lib/python2.7/site-packages/visbeat/Video.py", line 131, in loadFile
    self.reader = imageio.get_reader(self.a_info['file_path'], 'ffmpeg');
  File "/home/gx/anaconda3/envs/visbeat/lib/python2.7/site-packages/imageio/core/functions.py", line 129, in get_reader
    return format.get_reader(request)
  File "/home/gx/anaconda3/envs/visbeat/lib/python2.7/site-packages/imageio/core/format.py", line 169, in get_reader
    return self.Reader(self, request)
  File "/home/gx/anaconda3/envs/visbeat/lib/python2.7/site-packages/imageio/core/format.py", line 218, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/gx/anaconda3/envs/visbeat/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 327, in _open
    self._load_infos()
  File "/home/gx/anaconda3/envs/visbeat/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 479, in _load_infos
    raise IOError(fmt % err2)
IOError: Could not load meta information
=== stderr ===

Thanks....

**Comment by aszxnm** [comment]
Dear Sir,
            I'm a student from China,Can you provide the version of the installed python library?
            Thanks a lot.

**Comment by shenjing023** [comment]
@aszxnm ,did you solve this problem? How to install in python3,thanks.

**Comment by aszxnm** [comment]
> @aszxnm ,did you solve this problem? How to install in python3,thanks.

I installed it in python3.5， ran it and debug it，Not many bugs, you can try.

**Comment by aszxnm** [comment]
> @aszxnm ,did you solve this problem? How to install in python3,thanks.

I reloaded the environment and changed the library version to fix the problem

**Comment by shenjing023** [comment]
I installeded in py3.7 and something error: ModuleNotFoundError: No module named 'VisBeatImports'. after that, I installed in py2.7 success. But when import visbeat, error: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'. Then, run pip install imageio-ffmpeg, error, ERROR: Package 'imageio-ffmpeg' requires a different Python: 2.7.17 not in '>=3.4'. so how did you debug in py3.5, change the source code import path? such as " from VisBeatImports import * " change to " from .VisBeatImports import * " ?

**Comment by aszxnm** [comment]
> I installeded in py3.7 and something error: ModuleNotFoundError: No module named 'VisBeatImports'. after that, I installed in py2.7 success. But when import visbeat, error: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'. Then, run pip install imageio-ffmpeg, error, ERROR: Package 'imageio-ffmpeg' requires a different Python: 2.7.17 not in '>=3.4'. so how did you debug in py3.5, change the source code import path? such as " from VisBeatImports import * " change to " from .VisBeatImports import * " ?

pip install imageio==2.4.1

**Comment by aszxnm** [comment]
> I installeded in py3.7 and something error: ModuleNotFoundError: No module named 'VisBeatImports'. after that, I installed in py2.7 success. But when import visbeat, error: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'. Then, run pip install imageio-ffmpeg, error, ERROR: Package 'imageio-ffmpeg' requires a different Python: 2.7.17 not in '>=3.4'. so how did you debug in py3.5, change the source code import path? such as " from VisBeatImports import * " change to " from .VisBeatImports import * " ?

pip install imageio==2.4.1 in python=2.7

**Comment by shenjing023** [comment]
did you appear the error "ModuleNotFoundError: No module named 'VisBeatImports'" when you run in python3 ? thanks for your help

**Comment by aszxnm** [comment]
> did you appear the error "ModuleNotFoundError: No module named 'VisBeatImports'" when you run in python3 ? thanks for your help

Yes, in python=3.6.9 it appears too, and not in python=3.5

**Comment by shenjing023** [comment]
so how did you solve this?

**Comment by aszxnm** [comment]
I don't use it in python3.7, I'm sorry i can't solve it too.

**Comment by shenjing023** [comment]
are you use this library now?

**Comment by aszxnm** [comment]
Here's my environment now.
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
audioread                 2.1.8                    pypi_0    pypi
backports-functools-lru-cache 1.6.1                    pypi_0    pypi
beautifulsoup4            4.8.1                    pypi_0    pypi
bs4                       0.0.1                    pypi_0    pypi
ca-certificates           2019.10.16                    0    defaults
certifi                   2019.9.11                py27_0    defaults
cffi                      1.13.2                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.1                    pypi_0    pypi
enum34                    1.1.6                    pypi_0    pypi
funcsigs                  1.0.2                    pypi_0    pypi
futures                   3.3.0                    pypi_0    pypi
idna                      2.8                      pypi_0    pypi
imageio                   2.4.1                    pypi_0    pypi
joblib                    0.14.0                   pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
librosa                   0.7.1                    pypi_0    pypi
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
llvmlite                  0.30.0                   pypi_0    pypi
matplotlib                2.2.4                    pypi_0    pypi
moviepy                   1.0.1                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1    defaults
numba                     0.46.0                   pypi_0    pypi
numpy                     1.16.5                   pypi_0    pypi
openssl                   1.1.1d               h7b6447c_3    defaults
pillow                    6.2.1                    pypi_0    pypi
pip                       19.3.1                   py27_0    defaults
proglog                   0.1.9                    pypi_0    pypi
pycparser                 2.19                     pypi_0    pypi
pyparsing                 2.4.5                    pypi_0    pypi
python                    2.7.17               h9bab390_0    defaults
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2019.3                   pypi_0    pypi
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   pypi_0    pypi
resampy                   0.2.2                    pypi_0    pypi
scikit-learn              0.20.4                   pypi_0    pypi
scipy                     1.2.2                    pypi_0    pypi
setuptools                41.6.0                   py27_0    defaults
singledispatch            3.4.0.3                  pypi_0    pypi
six                       1.13.0                   pypi_0    pypi
some-package              0.1                      pypi_0    pypi
soundfile                 0.10.2                   pypi_0    pypi
soupsieve                 1.9.5                    pypi_0    pypi
sqlite                    3.30.1               h7b6447c_0    defaults
subprocess32              3.5.4                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.38.0                   pypi_0    pypi
urllib3                   1.25.7                   pypi_0    pypi
visbeat                   0.0.9                    pypi_0    pypi
wheel                     0.33.6                   py27_0    defaults
youtube-dl                2019.11.5                pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults

**Comment by shenjing023** [comment]
老哥，你还在做这方面的研究吗

**Comment by aszxnm** [comment]
> 老哥，你还在做这方面的研究吗

有看一部分，需要用。

**Comment by shenjing023** [comment]
介意加个qq讨论讨论吗，我qq1985529611

**Comment by wtnan2003** [comment]
@aszxnm @shenjing023  老哥们还对音乐动作踩点有研究吗，感觉如果动作和音乐风格差比较远，就调不出好效果
