### ISSUE TITLE
ModuleNotFoundError: No module named 'VisBeatImports'

### ISSUE THREAD

**Issue by zhongyi-zhou** [abedavis/visbeat#5]
Hello! I cannot load the package. Here is the bug information:
```
(visbeat) zhongyi@zhongyi-XPS-15-9560:~$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import visbeat as vb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhongyi/anaconda3/envs/visbeat/lib/python3.6/site-packages/visbeat/__init__.py", line 2, in <module>
    from VisBeatImports import *
ModuleNotFoundError: No module named 'VisBeatImports'
```

**Comment by zhongyi-zhou** [comment]
I have checked the error is maybe caused by the installed package is written for python2.

After I create the python 2.7 conda env, it seems that there comes another error:

```
>>> import visbeat
/home/zhongyi/anaconda3/envs/py2/lib/python2.7/site-packages/librosa/__init__.py:40: DeprecationWarning: You are using librosa with Python 2. Please note that librosa 0.7 will be the last version to support Python 2, after which it will require Python 3 or later.
  DeprecationWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhongyi/anaconda3/envs/py2/lib/python2.7/site-packages/visbeat/__init__.py", line 3, in <module>
    from Video import *
  File "/home/zhongyi/anaconda3/envs/py2/lib/python2.7/site-packages/visbeat/Video.py", line 7, in <module>
    import moviepy.editor as mpy
  File "/home/zhongyi/anaconda3/envs/py2/lib/python2.7/site-packages/moviepy/editor.py", line 30, in <module>
    imageio.plugins.ffmpeg.download()
  File "/home/zhongyi/anaconda3/envs/py2/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 40, in download
    "imageio.ffmpeg.download() has been deprecated. "
RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'

```


But after I install by 
```
pip install imageio-ffmpeg
```
Here is the error:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting imageio-ffmpeg
  Using cached https://files.pythonhosted.org/packages/44/51/8a16c76b2a19ac2af82001985c80d3caca4c373528855cb27e12b39373fb/imageio-ffmpeg-0.3.0.tar.gz
ERROR: imageio-ffmpeg requires Python '>=3.4' but the running Python is 2.7.16

```

**Comment by akoepke** [comment]
Downgrading imageio with ```pip install imageio==2.4.1``` fixed this problem for me (similar issue here: https://github.com/epic-kitchens/epic-lib/issues/69).

**Comment by malcolmgarner-movement** [comment]
Hi,
Question for @akoepke: what version of scipy do you have? as when I tried to install visbeat with python2, it errors out at scipy, stating the version needed for python is 3.5.

Let me know, and thanks again

**Comment by akoepke** [comment]
I used scipy version 1.2.2.

**Comment by aszxnm** [comment]
Hi,I meet a question.
Source: target.mp4
Target: mv.mp4
Video source at ./VisBeatAssets/VideoSources/target/
Calculating frames for target_Full...
Done.
Issue loading audio for ./VisBeatAssets/VideoSources/target/Versions/Source/Full/target.mp4
Issue loading audio for ./VisBeatAssets/VideoSources/target/Versions/Original/maxheight_240/target.mp4
Video source at ./VisBeatAssets/VideoSources/mv/
Calculating frames for mv_Full...
Done.
Warping target_240 to mv_240
None
Traceback (most recent call last):
  File "dancefer.py", line 40, in <module>
    main(args);
  File "dancefer.py", line 28, in main
    synch_audio_beat = 0);
  File "/home/guoxin/anaconda3/envs/visbeat/lib/python2.7/site-packages/visbeat/__init__.py", line 268, in AutoDancefer
    result =  Dancefer(source_video=sourcev, target=targetv, output_path=output_path, force_recompute = True, synch_audio_beat=synch_audio_beat, synch_video_beat=synch_video_beat, beat_offset=beat_offset,**kwargs)
  File "/home/guoxin/anaconda3/envs/visbeat/lib/python2.7/site-packages/visbeat/__init__.py", line 165, in Dancefer
    vbeats = vbeats[start_video_beat:];
TypeError: 'NoneType' object has no attribute '__getitem__'
How can i solve it?

**Comment by azahreba** [comment]
@JoeyChuuichi,
Hey! 👋
Did you manage to run the code?

**Comment by zhongyi-zhou** [comment]
@azahreba 
No. I write my own code based on the paper.

**Comment by azahreba** [comment]
@JoeyChuuichi 
Cool! Can you share it? ☺️🙏

**Comment by zhongyi-zhou** [comment]
> @JoeyChuuichi
> Cool! Can you share it?

Sure. I used it in one of my projects. I am now working on improving the code for open source. I will let you know after I publish it.

**Comment by RuoniWang** [comment]
@JoeyChuuichi I'd really appreciate it too! :)

**Comment by jsaluja** [comment]
> > @JoeyChuuichi
> > Cool! Can you share it?
> 
> Sure. I used it in one of my projects. I am now working on improving the code for open source. I will let you know after I publish it.

Can you share it ?

**Comment by mathigatti** [comment]
I tried python2 and imageio==2.4.1 and it worked great

Anyway python2 is a little bit old, I don't even have it in my machine so I made [this](https://colab.research.google.com/drive/1VGobRIKoFW8Old2dgzkWFx6ft2ASreh1?usp=sharing) browser version to run the code. You can try it, hope its useful :)

**Comment by ujlm** [comment]
Great job! However, is there a way to increase the resolution of the resulting video?
